### PR TITLE
mostly editorial stuff

### PR DESCRIPTION
**Pull request by wtarreau**
email address, broken sentence, one rule not to send 422 without early data, one rule not to unconditionally add early-data. The rest is left for discussion in the issues.

### CODE REVIEW

**Comment by martinthomson** [comment]
I cherry-picked the email address change, but this will probably want to wait for #3 to be resolved first.  The changes are good, but I don't want to lose them and that is guaranteed if we take #3.

**Comment by wtarreau** [comment]
Don't worry, drop them if that's easier for you at the moment, since they're in my tree I'll be able to rebase once the other changes are merged.

**Comment by martinthomson** [comment]
Looking at these changes, against the changes in the current version and those in the other open pull requests, I think that they have all been overtaken by events.  I'm happy to reopen if I misunderstood something.

**Comment by wtarreau** [comment]
No pb, I can recheck.

**Pull request closed without merging**
