### PR TITLE
Stuff II

### PR DESCRIPTION
**Pull request by mnot**
Mostly editorial, I think, but please review.

### CODE REVIEW

**Comment by wtarreau** [comment]
OK except for two : 
- "Early-Data isn't required now" : 
  The server can trigger a retry without the use of early data by responding
=> the wording seems less clear to me and seems to allow a retry to be performed outside of the scope of early data. I'd suggest something along "The server can retry a request indicating use of early data (either via the presence of the Early-Data header field or directly received as TLS early data) by responding ..."

- "downstream -> upstream" : upstream/downstream should be banned from normative text as we've seen in the past that it creates lots of confusion. Half of the participants consider downstream the one at the end of the request chain, and the other half consider downstream the one at the end of the response chain. Proposal : "... indicates that the 4NN status code will be understood by at least one agent in the chain".

**Comment by mnot** [comment]
WRT "early data isn't required" -- that's pretty clearly defined in the sections below; this section is about how servers should handle early data they receive.

WRT "downstream -> upstream" -- fair enough, will reengineer.

**Comment by wtarreau** [comment]
OK.

**Review by martinthomson — COMMENTED** [review]
The text about safe methods is new-ish, but welcome.

**Pull request merged**
